import TanstackQueryProvider from "@/components/tanstack-query/TanstackQueryProvider";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import StoreProvider from "../components/StoreProvider";

const NunitoSans = Nunito_Sans({
  weight: "300",
  subsets: ["latin-ext"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "MSGme",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StoreProvider>
        <html lang="en" suppressHydrationWarning={true}>
          <head>
            <script
              dangerouslySetInnerHTML={{
                __html: `
              (function() {
                const theme = localStorage.getItem('flowbite-theme-mode');
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
              }}
            />
          </head>
          <TanstackQueryProvider>
            <body
              className={
                NunitoSans.className +
                " " +
                " bg-bgColor dark:bg-customGrey-blackBg relative"
              }
              suppressHydrationWarning={true}
            >
              {children}
              <Toaster />
            </body>
          </TanstackQueryProvider>
        </html>
      </StoreProvider>
    </>
  );
}
